//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Litium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainNotification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainNotification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Litium.Resources.DomainNotification", typeof(DomainNotification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency with the same code already exists..
        /// </summary>
        public static string CurrencyExistsException {
            get {
                return ResourceManager.GetString("CurrencyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete last default language.
        /// </summary>
        public static string DeleteDefaultLanguageException {
            get {
                return ResourceManager.GetString("DeleteDefaultLanguageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete default web site..
        /// </summary>
        public static string DeleteDefaultWebSiteException {
            get {
                return ResourceManager.GetString("DeleteDefaultWebSiteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} has incompatible value.
        /// </summary>
        public static string EnumFormat {
            get {
                return ResourceManager.GetString("EnumFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with the same name already exists on the same level..
        /// </summary>
        public static string FolderNameExistsException {
            get {
                return ResourceManager.GetString("FolderNameExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} can&apos;t be less then thero..
        /// </summary>
        public static string IncompatibleCountValue {
            get {
                return ResourceManager.GetString("IncompatibleCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} can&apos;t be less thwn zero..
        /// </summary>
        public static string IncompatiblePriceValue {
            get {
                return ResourceManager.GetString("IncompatiblePriceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with the same culture already exists..
        /// </summary>
        public static string LanguageExistException {
            get {
                return ResourceManager.GetString("LanguageExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message is English.
        /// </summary>
        public static string LocalizationTestMessage {
            get {
                return ResourceManager.GetString("LocalizationTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t move entity to its child..
        /// </summary>
        public static string MoveToChildException {
            get {
                return ResourceManager.GetString("MoveToChildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} can&apos;t by null or empty.
        /// </summary>
        public static string NoNullOrEmpty {
            get {
                return ResourceManager.GetString("NoNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product {0} is out of stock. Please reduce the quantity or remove from order..
        /// </summary>
        public static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page display template with the same name for the same page type already exists..
        /// </summary>
        public static string PageDisplayTemplateNameExistsException {
            get {
                return ResourceManager.GetString("PageDisplayTemplateNameExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page with the same name already exists on the same level..
        /// </summary>
        public static string PageNameExistsException {
            get {
                return ResourceManager.GetString("PageNameExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page type with the same name already exists..
        /// </summary>
        public static string PageTypeExistsException {
            get {
                return ResourceManager.GetString("PageTypeExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page with the same url in the same web site already exists..
        /// </summary>
        public static string PageUrlExistsException {
            get {
                return ResourceManager.GetString("PageUrlExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with this e-mail alreay exists..
        /// </summary>
        public static string PersonEmailExistException {
            get {
                return ResourceManager.GetString("PersonEmailExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person with the same Login Name already exists..
        /// </summary>
        public static string PersonLoginExistException {
            get {
                return ResourceManager.GetString("PersonLoginExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} has invalide DateTime format for SQL Server data type..
        /// </summary>
        public static string SqlDateValide {
            get {
                return ResourceManager.GetString("SqlDateValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site with the same domain name already exists..
        /// </summary>
        public static string WebSiteDomainExistsException {
            get {
                return ResourceManager.GetString("WebSiteDomainExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site with the same name already exists..
        /// </summary>
        public static string WebSiteNameExistsException {
            get {
                return ResourceManager.GetString("WebSiteNameExistsException", resourceCulture);
            }
        }
    }
}
