//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Litium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebStroreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebStroreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Litium.Resources.WebStroreResource", typeof(WebStroreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add products.
        /// </summary>
        public static string AddProducts {
            get {
                return ResourceManager.GetString("AddProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6FD37C3-B05F-47F8-BF60-1A636564A46F.
        /// </summary>
        public static string ADMIN_ID {
            get {
                return ResourceManager.GetString("ADMIN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative page.
        /// </summary>
        public static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All campaign.
        /// </summary>
        public static string AllCampaign {
            get {
                return ResourceManager.GetString("AllCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All deliveries.
        /// </summary>
        public static string AllDeliveries {
            get {
                return ResourceManager.GetString("AllDeliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selected products successfully assigned to product set.
        /// </summary>
        public static string AssignProductSetComplete {
            get {
                return ResourceManager.GetString("AssignProductSetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign to selected category.
        /// </summary>
        public static string AssignToCategory {
            get {
                return ResourceManager.GetString("AssignToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by brands.
        /// </summary>
        public static string BrandsHeader {
            get {
                return ResourceManager.GetString("BrandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type-submit t-button t-grid-update t-button-icon.
        /// </summary>
        public static string ButtonTypeImageStyle {
            get {
                return ResourceManager.GetString("ButtonTypeImageStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string CampaignActive {
            get {
                return ResourceManager.GetString("CampaignActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign description.
        /// </summary>
        public static string CampaignDescription {
            get {
                return ResourceManager.GetString("CampaignDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiish campaign date.
        /// </summary>
        public static string CampaignEndDate {
            get {
                return ResourceManager.GetString("CampaignEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string CampaignHeader {
            get {
                return ResourceManager.GetString("CampaignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign name.
        /// </summary>
        public static string CampaignName {
            get {
                return ResourceManager.GetString("CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign price.
        /// </summary>
        public static string CampaignPrice {
            get {
                return ResourceManager.GetString("CampaignPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start campaign date.
        /// </summary>
        public static string CampaignStartDate {
            get {
                return ResourceManager.GetString("CampaignStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign types.
        /// </summary>
        public static string CampaignTypes {
            get {
                return ResourceManager.GetString("CampaignTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CART.
        /// </summary>
        public static string CART {
            get {
                return ResourceManager.GetString("CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For assign product to category please drug and drop selected products over concrete category.
        /// </summary>
        public static string CategoryCreateNote {
            get {
                return ResourceManager.GetString("CategoryCreateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by category.
        /// </summary>
        public static string CategoryFilter {
            get {
                return ResourceManager.GetString("CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter product.
        /// </summary>
        public static string CategoryGridFilter {
            get {
                return ResourceManager.GetString("CategoryGridFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        public static string CategoryNull {
            get {
                return ResourceManager.GetString("CategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category.
        /// </summary>
        public static string CategoryParent {
            get {
                return ResourceManager.GetString("CategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change delivery address.
        /// </summary>
        public static string ChangeDeliveryAddress {
            get {
                return ResourceManager.GetString("ChangeDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update order states.
        /// </summary>
        public static string ChangeOrderOption {
            get {
                return ResourceManager.GetString("ChangeOrderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choise payment method.
        /// </summary>
        public static string ChoicePaymentMethod {
            get {
                return ResourceManager.GetString("ChoicePaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chouse product for campaign.
        /// </summary>
        public static string ChouseProductsToAssign {
            get {
                return ResourceManager.GetString("ChouseProductsToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ColAddress {
            get {
                return ResourceManager.GetString("ColAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last enter.
        /// </summary>
        public static string ColLastLogin {
            get {
                return ResourceManager.GetString("ColLastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ColLoginName {
            get {
                return ResourceManager.GetString("ColLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete registration.
        /// </summary>
        public static string CompleteRegistration {
            get {
                return ResourceManager.GetString("CompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / edit delivery.
        /// </summary>
        public static string CreateEditDelivery {
            get {
                return ResourceManager.GetString("CreateEditDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new campaign.
        /// </summary>
        public static string CreateNewCampaign {
            get {
                return ResourceManager.GetString("CreateNewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new delivery.
        /// </summary>
        public static string CreateNewDelivery {
            get {
                return ResourceManager.GetString("CreateNewDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product Set.
        /// </summary>
        public static string CreateNewProductSet {
            get {
                return ResourceManager.GetString("CreateNewProductSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usd.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current campaign.
        /// </summary>
        public static string CurrentCampaign {
            get {
                return ResourceManager.GetString("CurrentCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current product sets.
        /// </summary>
        public static string CurrentProductSets {
            get {
                return ResourceManager.GetString("CurrentProductSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete campaign.
        /// </summary>
        public static string DeleteCampaign {
            get {
                return ResourceManager.GetString("DeleteCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected campaign. Notice that product wouldn&apos;t be deleted..
        /// </summary>
        public static string DeleteCampaignConfirm {
            get {
                return ResourceManager.GetString("DeleteCampaignConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete thouse categories. If category has child categories it\&apos;s will be deleted also..
        /// </summary>
        public static string DeleteCategoryConfirm {
            get {
                return ResourceManager.GetString("DeleteCategoryConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete delivery.
        /// </summary>
        public static string DeleteDelivery {
            get {
                return ResourceManager.GetString("DeleteDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product set.
        /// </summary>
        public static string DeleteProductSet {
            get {
                return ResourceManager.GetString("DeleteProductSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected product set. Notice that product wouldn&apos;t be deleleted..
        /// </summary>
        public static string DeleteProductSetConfirm {
            get {
                return ResourceManager.GetString("DeleteProductSetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete selected product set?.
        /// </summary>
        public static string DeleteProductSetConfirmation {
            get {
                return ResourceManager.GetString("DeleteProductSetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery description.
        /// </summary>
        public static string DeliveryDescription {
            get {
                return ResourceManager.GetString("DeliveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string DeliveryHeader {
            get {
                return ResourceManager.GetString("DeliveryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery payment.
        /// </summary>
        public static string DeliveryPayment {
            get {
                return ResourceManager.GetString("DeliveryPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will you buy somethings in oour store?.
        /// </summary>
        public static string DidYouBoughtSomethings {
            get {
                return ResourceManager.GetString("DidYouBoughtSomethings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download orders.
        /// </summary>
        public static string DownloadOrders {
            get {
                return ResourceManager.GetString("DownloadOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select end synchronization date.
        /// </summary>
        public static string EndSynchDate {
            get {
                return ResourceManager.GetString("EndSynchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create entity before upload some image.
        /// </summary>
        public static string EnityGuidEmptyException {
            get {
                return ResourceManager.GetString("EnityGuidEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter by your name.
        /// </summary>
        public static string EnterYourAccount {
            get {
                return ResourceManager.GetString("EnterYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period in days when campaign is active.
        /// </summary>
        public static string ExpirationPeriod {
            get {
                return ResourceManager.GetString("ExpirationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export orders.
        /// </summary>
        public static string ExportOrders {
            get {
                return ResourceManager.GetString("ExportOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to cart.
        /// </summary>
        public static string GotoCart {
            get {
                return ResourceManager.GetString("GotoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to order.
        /// </summary>
        public static string HowToOrder {
            get {
                return ResourceManager.GetString("HowToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import products.
        /// </summary>
        public static string ImportProducts {
            get {
                return ResourceManager.GetString("ImportProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalide user name or password..
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last synchronization.
        /// </summary>
        public static string LastSynchDate {
            get {
                return ResourceManager.GetString("LastSynchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string LeftMenuHeader {
            get {
                return ResourceManager.GetString("LeftMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password. Please try again..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login / Registration.
        /// </summary>
        public static string LoginRegistration {
            get {
                return ResourceManager.GetString("LoginRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyality program.
        /// </summary>
        public static string LoyalityProgram {
            get {
                return ResourceManager.GetString("LoyalityProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show..
        /// </summary>
        public static string NoGridRecords {
            get {
                return ResourceManager.GetString("NoGridRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has not supported format. The format file should be .xml.
        /// </summary>
        public static string NotSupportedFormat {
            get {
                return ResourceManager.GetString("NotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No number has setted.
        /// </summary>
        public static string NullOrderNumberText {
            get {
                return ResourceManager.GetString("NullOrderNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images is alloved to upload..
        /// </summary>
        public static string OnlyImagesIsAllovedToUpload {
            get {
                return ResourceManager.GetString("OnlyImagesIsAllovedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank for your buying.
        /// </summary>
        public static string OrderCompleteResult {
            get {
                return ResourceManager.GetString("OrderCompleteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe your delivery time..
        /// </summary>
        public static string OrderDescription {
            get {
                return ResourceManager.GetString("OrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order description.
        /// </summary>
        public static string OrderDescription1 {
            get {
                return ResourceManager.GetString("OrderDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderFrom {
            get {
                return ResourceManager.GetString("OrderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order state.
        /// </summary>
        public static string OrderState {
            get {
                return ResourceManager.GetString("OrderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order summa.
        /// </summary>
        public static string OrderSumma {
            get {
                return ResourceManager.GetString("OrderSumma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Total.
        /// </summary>
        public static string OrderTotal {
            get {
                return ResourceManager.GetString("OrderTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product {0} is out of stock. Please reduce quantity or remove from bascet..
        /// </summary>
        public static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has changed.
        /// </summary>
        public static string PasswordChangedSuccessful {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign percent for product set.
        /// </summary>
        public static string PercentByProductSetCampaign {
            get {
                return ResourceManager.GetString("PercentByProductSetCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent of discount.
        /// </summary>
        public static string PercentDiscount {
            get {
                return ResourceManager.GetString("PercentDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string PersonActive {
            get {
                return ResourceManager.GetString("PersonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal campaign.
        /// </summary>
        public static string PersonalCampaign {
            get {
                return ResourceManager.GetString("PersonalCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal campaign.
        /// </summary>
        public static string PersonalCampaignHeader {
            get {
                return ResourceManager.GetString("PersonalCampaignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal discount.
        /// </summary>
        public static string PersonalDiscount {
            get {
                return ResourceManager.GetString("PersonalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal profile.
        /// </summary>
        public static string PersonalProfile {
            get {
                return ResourceManager.GetString("PersonalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address.
        /// </summary>
        public static string PersonalUserAddress {
            get {
                return ResourceManager.GetString("PersonalUserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalUserData {
            get {
                return ResourceManager.GetString("PersonalUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string PhoneHome {
            get {
                return ResourceManager.GetString("PhoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string PhoneMobile {
            get {
                return ResourceManager.GetString("PhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Last Name.
        /// </summary>
        public static string PIB {
            get {
                return ResourceManager.GetString("PIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign price for product.
        /// </summary>
        public static string PriceByProductCampaign {
            get {
                return ResourceManager.GetString("PriceByProductCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brend.
        /// </summary>
        public static string ProductBrend {
            get {
                return ResourceManager.GetString("ProductBrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string ProductCapacity {
            get {
                return ResourceManager.GetString("ProductCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by product category.
        /// </summary>
        public static string ProductCategoryFilter {
            get {
                return ResourceManager.GetString("ProductCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ProductCountry {
            get {
                return ResourceManager.GetString("ProductCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product filter.
        /// </summary>
        public static string ProductFilter {
            get {
                return ResourceManager.GetString("ProductFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filder by product name.
        /// </summary>
        public static string ProductNameFilter {
            get {
                return ResourceManager.GetString("ProductNameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new product set.
        /// </summary>
        public static string ProductSetCreate {
            get {
                return ResourceManager.GetString("ProductSetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ProductSetDelete {
            get {
                return ResourceManager.GetString("ProductSetDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductSetDescription {
            get {
                return ResourceManager.GetString("ProductSetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sets.
        /// </summary>
        public static string ProductSetHeader {
            get {
                return ResourceManager.GetString("ProductSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product set name.
        /// </summary>
        public static string ProductSetName {
            get {
                return ResourceManager.GetString("ProductSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product has updated.
        /// </summary>
        public static string ProductUpdatedSuccesfull {
            get {
                return ResourceManager.GetString("ProductUpdatedSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string ProductWeight {
            get {
                return ResourceManager.GetString("ProductWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If some products is unchecked they will be unpublished. Continue?.
        /// </summary>
        public static string PublishConfirmation {
            get {
                return ResourceManager.GetString("PublishConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration form.
        /// </summary>
        public static string RegistrationForm {
            get {
                return ResourceManager.GetString("RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save campaign.
        /// </summary>
        public static string SaveCampaign {
            get {
                return ResourceManager.GetString("SaveCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save delivery.
        /// </summary>
        public static string SaveDelivery {
            get {
                return ResourceManager.GetString("SaveDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save products.
        /// </summary>
        public static string SaveProducts {
            get {
                return ResourceManager.GetString("SaveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search has no result.
        /// </summary>
        public static string SearchHasNoResult {
            get {
                return ResourceManager.GetString("SearchHasNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select products campaign.
        /// </summary>
        public static string SelectProductCampaign {
            get {
                return ResourceManager.GetString("SelectProductCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set image for category.
        /// </summary>
        public static string SetImageForCategory {
            get {
                return ResourceManager.GetString("SetImageForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string SetOrder {
            get {
                return ResourceManager.GetString("SetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select start synchronization date.
        /// </summary>
        public static string StartSynchDate {
            get {
                return ResourceManager.GetString("StartSynchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock balance.
        /// </summary>
        public static string StockBalance {
            get {
                return ResourceManager.GetString("StockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order was created.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved succesfully.
        /// </summary>
        public static string Succesfull {
            get {
                return ResourceManager.GetString("Succesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summa.
        /// </summary>
        public static string Summa {
            get {
                return ResourceManager.GetString("Summa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User have to buy to satisfy rule of campaign .
        /// </summary>
        public static string SummaryBought {
            get {
                return ResourceManager.GetString("SummaryBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization configuration.
        /// </summary>
        public static string SynchConfig {
            get {
                return ResourceManager.GetString("SynchConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string Synchronization {
            get {
                return ResourceManager.GetString("Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top category.
        /// </summary>
        public static string TopCategory {
            get {
                return ResourceManager.GetString("TopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        public static string Uncategorized {
            get {
                return ResourceManager.GetString("Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F0230CD1-A07F-4F25-A120-785427D3CDA6.
        /// </summary>
        public static string UncategorizedId {
            get {
                return ResourceManager.GetString("UncategorizedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;span class=&apos;t-icon t-update&apos;/&amp;gt;.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update campaign.
        /// </summary>
        public static string UpdateCampaign {
            get {
                return ResourceManager.GetString("UpdateCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laste update.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update product set.
        /// </summary>
        public static string UpdateProductSet {
            get {
                return ResourceManager.GetString("UpdateProductSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile updated successfully.
        /// </summary>
        public static string UpdateProfileSuccessful {
            get {
                return ResourceManager.GetString("UpdateProfileSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User history.
        /// </summary>
        public static string UserHistory {
            get {
                return ResourceManager.GetString("UserHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View orders history.
        /// </summary>
        public static string ViewOrderHistory {
            get {
                return ResourceManager.GetString("ViewOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome {0}, now you can enter your profile.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To follow you should fill in your personal data.
        /// </summary>
        public static string YouNeedToCompleteYourData {
            get {
                return ResourceManager.GetString("YouNeedToCompleteYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order.
        /// </summary>
        public static string YourOrder {
            get {
                return ResourceManager.GetString("YourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart is empty.
        /// </summary>
        public static string YourShoppingCartIsEmpty {
            get {
                return ResourceManager.GetString("YourShoppingCartIsEmpty", resourceCulture);
            }
        }
    }
}
